### ISSUE TITLE
Radix Question

### ISSUE THREAD

**Issue by openpowerwtf** [antonblanchard/microwatt#418]
In the mmu state machine state 'SEGMENT_CHECK':

`v.shift := r.shift + (31 - 12) - mbits;`

Shouldn't this account for the fact that Root Page Directory Size = 2**(mbits+3)?  i.e.

`v.shift := r.shift + (31 - 12) - mbits - 3;`

With the above change I get my expected PDE fetch address.

**Comment by paulusmack** [comment]
I think it's correct as it is, actually.

The previous state (PROC_TBL_WAIT) set r.shift = RTS and r.mask_size = RPDS from the process table entry. The total number of address bits mapped by the radix tree is 2^(RTS + 31), hence the +31. The address generation logic ignores the bottom 12 bits, hence the -12. The logic is:

```
        pgtable_addr := x"00" & r.pgbase(55 downto 19) &
                        ((r.pgbase(18 downto 3) and not mask) or (addrsh and mask)) &
                        "000";
```

where mask = (1 << r.mask_size) - 1 and addrsh = r.addr >> (r.shift + 12).

The '& "000"' at the end accounts for the fact that each entry in the root page directory is 8 bytes. Basically the RPDS field is exactly the number of bits we need to take from the address being translated in order to index the root page directory.

As an experiment, I tried making the change you suggest. The result was that Linux doesn't boot, but crashes very early. The kernel MMU code is exactly the same as on a P9 or P10 --- there is no microwatt-specific code in there. The kernel boots just fine without that change.
